---

- hosts: all
  become: true
  tasks:

  - name: install apache, ntp and php package
    package:
      update_cache: yes
      name: 
        - "{{ server_web}}"
        - "{{ pachet_php }}"
        - "{{ pachet_ntp}}"
      state: latest	
    when: ansible_distribution == "CentOS"  

  