---

- hosts: all
  become: true
  tasks:

  - name: uninstall apache, ntp and php package
    package:
      update_cache: yes
      name: 
        - httpd
        - php
        - ntp
      state: absent	
      