---

- hosts: all
  become: true
  pre_tasks: 
  - name: install updates
    tags: always
    yum: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks: 
    - name: install apache and php packages
      tags: apache, php
      package:
        name: 
          - httpd
          - php  
        state: latest
      when: ansible_distribution == "CentOS"
    
    - name: copiere fisiere
      tags: copy_files
      copy: 
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks: 
    - name: install mariadb package
      tags: MariaDB
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"

- hosts: file_servers 
  become: true
  tasks: 
    - name: install samba
      tags: samba
      package:
        name: samba
        state: latest

